name: opensuse-tumbleweed

on:
  schedule:
    - cron: '0 0 2,16 * *'

jobs:
  build:
    strategy:
      matrix:
        include:
          - arch: x86_64
            compat-distro-version: tumbleweed
            kernel: 5.15.x
          - arch: x86
            compat-distro-version: tumbleweed
            kernel: 5.10.x
    if: github.repository == 'puppylinux-woof-CE/woof-CE'
    uses: ./.github/workflows/build.yml
    with:
      repo: ${{ github.repository }}
      ref: ${{ github.ref }}
      arch: ${{ matrix.arch }}
      compat-distro: opensuse
      compat-distro-version: ${{ matrix.compat-distro-version }}
      kernel: ${{ matrix.kernel }}
      artifact: opensuse-${{ matrix.compat-distro-version }}-${{ github.run_number }}
      retention: 16
